-- Tables
COMMENT ON TABLE ab_data.amino_acid_sequences IS 'Antibody amino acid heavy and light chain sequences are defined here. ';
COMMENT ON TABLE ab_data.antibody_documents IS 'Details for documents related to antibodies (PDFs, Word documents, etc) are recorded here. The documents themselves are stored on a file shareand are registered here when uploaded by the client.';
COMMENT ON TABLE ab_data.antibody_information IS 'Defines all key details for antibody molecules except the actual heavy and light chain amino acid sequences which are defined in the "amino_acid_sequences" table.';
COMMENT ON TABLE ab_data.antibody_notes IS 'Extra details of interest to users about a particular antibody molecule can be defined here.';
COMMENT ON TABLE ab_data.antibody_notes_to_information IS 'A join table between "antibody_notes" and "antibody_information".';
COMMENT ON TABLE ab_data.antibody_sources IS 'A lookup table that defines the where the antibodies entries in the database originate from.  It can only be updated by an administrator.';
COMMENT ON TABLE ab_data.antibody_types IS 'A lookup table that defines the isotypes of antibodies.  It can only be updated by an administrator.';
COMMENT ON TABLE ab_data.documents_to_antibodies IS 'A join table between "antibody_documents" and "antibody_information".';
COMMENT ON TABLE ab_data.progeny_amino_acid_sequences IS 'Defines the parent-progeny relationship that can exist between antibody sequences where the progeny are deliberately mutated versions of a particular heavy or light chain amino acid sequence.';
COMMENT ON TABLE ab_data.seq_notes_to_aa_seq IS 'A join table between "amino_acid_sequencess" and "sequence_notes".';
COMMENT ON TABLE ab_data.sequence_notes IS 'Extra details of interest to users about a particular amino acid sequence can be defined here.';
COMMENT ON TABLE ab_data.sequences_to_information IS 'A join table between "amino_acid_sequencess" and "antibody_information".';
COMMENT ON TABLE ab_data.usernames IS 'A lookup table that stores a list of user names for accounts that can enter and view data.  Administrator account names are deliberately excluded from this table to ensure that data is entered by ordinary  users who are members of the "mabmindergroup" role. It can only be updated by an administrator.';

-- Columns
COMMENT ON COLUMN ab_data.amino_acid_sequences.amino_acid_sequence IS 'The single letter amino acid sequence of an antibody heavy or light chain or fragment thereof. By default the stored function that inserts this value restricts the letters to the standard 20 amino acids.';
COMMENT ON COLUMN ab_data.amino_acid_sequences.amino_acid_sequence_id IS 'The MD5 hash value calculated from the amino acid sequence where white space is removed and all letters are converted to uppercase.';
COMMENT ON COLUMN ab_data.amino_acid_sequences.chain_type IS 'This is either H, L or NULL but the rule is not enforced. Might need to set a constraint on this value.';
COMMENT ON COLUMN ab_data.amino_acid_sequences.sequence_name IS 'For sequences associated with an antibody this will be the antibody name concatenated to the chain type. For sequences not associated with an antibody, it can be any name the user chooses';
COMMENT ON COLUMN ab_data.amino_acid_sequences.created_by IS 'System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.amino_acid_sequences.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.amino_acid_sequences.last_modified_date IS 'The date /time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.amino_acid_sequences.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_documents.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_documents.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.antibody_documents.document_description IS 'A user-defined description of an uploaded document relevant to an antibody that is referenced in the database but stored on the file share.';
COMMENT ON COLUMN ab_data.antibody_documents.document_name IS 'The name given to the document and the name used by the file share.';
COMMENT ON COLUMN ab_data.antibody_documents.file_checksum IS 'The result of the R tools:md5sum function for a file. Files with the same value are assumed to be the same file.';
COMMENT ON COLUMN ab_data.antibody_documents.last_modified_date IS 'The date /time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.antibody_documents.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_information.antibody_source IS 'A foreign key referencing "antibody_sources" lookup table. Can be used to determine if it is a commercial therapeutic antibody, a research or internal candidate antibody .';
COMMENT ON COLUMN ab_data.antibody_information.antibody_type IS 'A foreign key referencing "antibody_types" lookup table. Defines the isotype of the antibody and indicates its species and whether it is humanised chimeric or purely of one species.';
COMMENT ON COLUMN ab_data.antibody_information.antibody_url IS 'A link to where the antibody information and sequence (if available) was taken from. Internal antibodies will be NULL for this column.';
COMMENT ON COLUMN ab_data.antibody_information.common_identifier IS 'This defines the name by which the antibody is known. It is a very important value in the database generally. If a USAN name, e.g. Daratumumab, is available, it is used. Internal antibodies use the name by which the antibody is known within the company.';
COMMENT ON COLUMN ab_data.antibody_information.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_information.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.antibody_information.last_modified_date IS 'The date /time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.antibody_information.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_information.target_gene_name IS 'The given name for the gene to which the antibody binds. No restriction on the gene names at present, they are free text. May need to re-visit this.';
COMMENT ON COLUMN ab_data.antibody_notes.antibody_note_id IS 'A SERIAL primary key for entries into this table.';
COMMENT ON COLUMN ab_data.antibody_notes.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_notes.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.antibody_notes.last_modified_date IS 'The date /time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.antibody_notes.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_notes.note_text IS 'Free text entered by the user to record some piece of information of relevance to a sequence in the "amino_acid_sequences" table.';
COMMENT ON COLUMN ab_data.antibody_notes_to_information.antibody_note_id IS 'A SERIAL primary key for entries into this table.';
COMMENT ON COLUMN ab_data.antibody_notes_to_information.common_identifier IS 'A foreign key value relating the note to the antibody it refers to.';
COMMENT ON COLUMN ab_data.antibody_notes_to_information.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_notes_to_information.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.antibody_notes_to_information.last_modified_date IS 'The date /time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.antibody_notes_to_information.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.antibody_sources.source_name IS 'A foreign key referencing what the antibody source is.';
COMMENT ON COLUMN ab_data.antibody_types.antibody_type IS 'A foreign key referencing what the antibody type is.';
COMMENT ON COLUMN ab_data.documents_to_antibodies.common_identifier IS 'A foreign key referencing the antibody name';
COMMENT ON COLUMN ab_data.documents_to_antibodies.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.documents_to_antibodies.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.documents_to_antibodies.file_checksum IS 'A foreign key referencing the uploaded file checksum.';
COMMENT ON COLUMN ab_data.documents_to_antibodies.last_modified_date IS 'The date /time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.documents_to_antibodies.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.progeny_amino_acid_sequences.amino_acid_parent_sequence_id IS 'The ID for a sequence (MD5 hash) for an antibody sequence that is defined as a "parent" and that has "progeny"';
COMMENT ON COLUMN ab_data.progeny_amino_acid_sequences.amino_acid_progeny_sequence_id IS 'The ID for a sequence (MD5 hash) for an antibody sequence that is defined as a "progeny" sequence. Current business rules enforce that a "progeny" sequence can have only one parent.';
COMMENT ON COLUMN ab_data.progeny_amino_acid_sequences.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.progeny_amino_acid_sequences.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.progeny_amino_acid_sequences.last_modified_date IS 'The date/time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.progeny_amino_acid_sequences.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.seq_notes_to_aa_seq.amino_acid_sequence_id IS 'A foreign key that references the sequence_id for the note.';
COMMENT ON COLUMN ab_data.seq_notes_to_aa_seq.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.seq_notes_to_aa_seq.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.seq_notes_to_aa_seq.last_modified_date IS 'The date/time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.seq_notes_to_aa_seq.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.seq_notes_to_aa_seq.sequence_note_id IS 'A SERIAL primary key for entries into this table.';
COMMENT ON COLUMN ab_data.sequence_notes.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.sequence_notes.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.sequence_notes.last_modified_date IS 'The date/time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.sequence_notes.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.sequence_notes.note_text IS 'Free text entered by the user to record some piece of information of relevance to a sequence in the "amino_acid_sequences" table.';
COMMENT ON COLUMN ab_data.sequence_notes.sequence_note_id IS 'A SERIAL primary key for entries into this table.';
COMMENT ON COLUMN ab_data.sequences_to_information.amino_acid_sequence_id IS 'A foreign key referencing the amino acid sequence entry for the antibody it is linked with.';
COMMENT ON COLUMN ab_data.sequences_to_information.common_identifier IS 'A foreign key referencing the antibody entry for the sequence it is linked with.';
COMMENT ON COLUMN ab_data.sequences_to_information.created_by IS 'Who created the row. System generated and defaults to current user. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.sequences_to_information.date_added IS 'The date /time/timezone on which the row was added. System-generated and defaults to "NOW()"';
COMMENT ON COLUMN ab_data.sequences_to_information.last_modified_date IS 'The date/time/timezone on which the row was edited. System-generated and defaults to "NOW()" and is automatically updated by a trigger.';
COMMENT ON COLUMN ab_data.sequences_to_information.modified_by IS 'Who edited the row. Automatically updated by a trigger. User must be defined in "usernames" table.';
COMMENT ON COLUMN ab_data.usernames.username IS 'The accounter holder name of a non-admin user.';
-- Views
COMMENT ON VIEW ab_data.vw_antibodies_information_and_sequence IS 'Brings together the H and L sequences with the antibody information for all antibodies entered into the system. This view can be filtered by client code';
COMMENT ON VIEW ab_data.vw_amino_acid_sequences_not_linked_to_ab IS 'Displayes all amino acid sequence entries that are not linked to an antibody.';

