CREATE TABLE hgnc_genes(
    hgnc_id TEXT NOT NULL,
    symbol TEXT,
    name TEXT,
    locus_group TEXT,
    locus_type TEXT,
    status TEXT,
    location TEXT,
    location_sortable TEXT,
    alias_symbol TEXT,
    alias_name TEXT,
    prev_symbol TEXT,
    prev_name TEXT,
    gene_family TEXT,
    gene_family_id TEXT,
    date_approved_reserved TEXT,
    date_symbol_changed TEXT,
    date_name_changed TEXT,
    date_modified TEXT,
    entrez_id TEXT,
    ensembl_gene_id TEXT,
    vega_id TEXT,
    ucsc_id TEXT,
    ena TEXT,
    refseq_accession TEXT,
    ccds_id TEXT,
    uniprot_ids TEXT,
    pubmed_id TEXT,
    mgd_id TEXT,
    rgd_id TEXT,
    lsdb TEXT,
    cosmic TEXT,
    omim_id TEXT,
    mirbase TEXT,
    homeodb TEXT,
    snornabase TEXT,
    bioparadigms_slc TEXT,
    orphanet TEXT,
    "pseudogene.org" TEXT,
    horde_id TEXT,
    merops TEXT,
    imgt TEXT,
    iuphar TEXT,
    kznf_gene_catalog TEXT,
    "mamit-trnadb" TEXT,
    cd TEXT,
    lncrnadb TEXT,
    enzyme_id TEXT,
    intermediate_filament_db TEXT,
    CONSTRAINT hgnc_genes_pk PRIMARY KEY (hgnc_id)
);
CREATE UNIQUE INDEX hgnc_genes_gene_symbol_idx ON hgnc_genes(symbol);

CREATE TABLE gene_names_lookup(
    gene_name_lookup_id INTEGER,
    hgnc_id TEXT,
    gene_identifier TEXT,
    identifier_type TEXT,
    tsv TEXT,
    CONSTRAINT gene_names_lookup_pkey PRIMARY KEY (gene_name_lookup_id)
);
CREATE INDEX gene_names_lu_idx ON gene_names_lookup(hgnc_id, gene_identifier);


